// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdjReKLriADTrQSaQS3ng16GgsrTnx9qM',
    appId: '1:777515238310:web:4d37f2fab62744e9340567',
    messagingSenderId: '777515238310',
    projectId: 'treecare-1c23a',
    authDomain: 'treecare-1c23a.firebaseapp.com',
    databaseURL: 'https://treecare-1c23a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'treecare-1c23a.firebasestorage.app',
    measurementId: 'G-5T4MJRJF3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs97xt4TJ8IB978CuKzjFiO7VK2YBeFcs',
    appId: '1:777515238310:android:d1332fab00640203340567',
    messagingSenderId: '777515238310',
    projectId: 'treecare-1c23a',
    databaseURL: 'https://treecare-1c23a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'treecare-1c23a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdjReKLriADTrQSaQS3ng16GgsrTnx9qM',
    appId: '1:777515238310:web:4d37f2fab62744e9340567',
    messagingSenderId: '777515238310',
    projectId: 'treecare-1c23a',
    authDomain: 'treecare-1c23a.firebaseapp.com',
    databaseURL: 'https://treecare-1c23a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'treecare-1c23a.firebasestorage.app',
    measurementId: 'G-5T4MJRJF3F',
  );
}
